version: "2"
run:
  tests: false
linters:
  enable:
    - modernize
    - prealloc
    # - tagalign
    - tagliatelle
    - perfsprint
    - asciicheck
    - bidichk
    # - gocognit # cyclop
    - decorder
    - dupl
    - gocritic
    - bodyclose
    - gosec
    - nilerr
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - staticcheck
    - zerologlint
    - goheader
  exclusions:
    generated: lax
    presets:
      - common-false-positives
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    goheader:
      values:
        const:
          LICENSE: GPL-2.0-only
          SOURCE: github.com/woozymasta/lzo
      template: |-
        SPDX-License-Identifier: {{ LICENSE }}
        Source: {{ SOURCE }}
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
